# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.TextField()),
                ('comment_email', models.EmailField(max_length=254)),
                ('comment_recall', models.TextField()),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
