# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidays_name', models.TextField()),
                ('holidays_description', models.TextField()),
                ('holidays_days', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
