# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holidays_description',
            field=models.TextField(default='Cегодня праздников нет!'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='holidays_name',
            field=models.TextField(default='Ничего'),
        ),
    ]
