# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
