# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170403_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateBirth',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.ImageField(blank=True, max_length=12, upload_to=''),
        ),
    ]
