# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170403_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=12),
        ),
    ]
