# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0002_auto_20161224_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notes_user',
        ),
    ]
