# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0003_remove_note_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notes_date',
            field=models.CharField(max_length=11),
        ),
    ]
