# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sketch', '0004_auto_20161228_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes_priority',
            field=models.IntegerField(default=0),
        ),
    ]
