# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0006_auto_20170209_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notes_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 13, 17, 45, 56, 34411)),
        ),
    ]
