# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0007_auto_20170213_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notes_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
