# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0008_auto_20170214_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notes_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
